// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcsz1qlRKQB5U1jq8vfbYIlBmWZGqWUj0',
    appId: '1:184956622503:web:c1a283e4ece64110d2ad82',
    messagingSenderId: '184956622503',
    projectId: 'divi-pro-c63b1',
    authDomain: 'divi-pro-c63b1.firebaseapp.com',
    storageBucket: 'divi-pro-c63b1.firebasestorage.app',
    measurementId: 'G-0DY33W2VQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Siv-iH2w6zEw7Kub1BoF5Y5HGRjDjdk',
    appId: '1:184956622503:android:8db40403d3d9669dd2ad82',
    messagingSenderId: '184956622503',
    projectId: 'divi-pro-c63b1',
    storageBucket: 'divi-pro-c63b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC80479It5f__CseVkkgcs3ODhNYObAoiU',
    appId: '1:184956622503:ios:d422f9c2517ec637d2ad82',
    messagingSenderId: '184956622503',
    projectId: 'divi-pro-c63b1',
    storageBucket: 'divi-pro-c63b1.firebasestorage.app',
    iosClientId: '184956622503-a988acodvg7rv5ol54f7di4jga4m056n.apps.googleusercontent.com',
    iosBundleId: 'com.divipro.OptiGest',
  );

}